### ISSUE TITLE
Attendance code appears in other events and disappears after refresh

### ISSUE THREAD

**Issue by binerys** [ucladevx/membership-portal#3]
## Expected Behavior
The code should only appear in the event I entered it in. Also shouldn't disappear after refresh.

## Current Behavior
Disappears and appears across all events

## Screenshot(s) 
![screen shot 2017-08-08 at 10 32 47 pm](https://user-images.githubusercontent.com/9737156/29106523-58761784-7c8a-11e7-89ff-eb5d8ece3ca5.png)

## Steps to Reproduce 
1. Select an event and enter the attendance code
2. Without refreshing the page, view another event in the list. You'll see the attendance code you entered in the former event
3. Refresh the page and you'll see the attendance code is gone from the form

## Your Environment 

- [x] __Desktop__:  
Operating System:  
- [x] Chrome (__Version:__ )
- [ ] Firefox (__Version:__ )
- [ ] Safari (__Version:__ )
- [ ] Opera (__Version:__ )
- [ ] IE (__Version:__ )
- [ ] EDGE (__Version:__ )

**Comment by nkansal96** [comment]
The first part is a frontend bug. It has been resolved in this commit: https://github.com/ucladevx/governor-acm/commit/e395d0e46406a6b25bb056be3818cd2fadcc982f

**Comment by nkansal96** [comment]
resolved: https://github.com/ucladevx/membership-portal/commit/c9d086df0620f9d9017f29e6bb42090b4da66a80
