### ISSUE TITLE
More descriptive error messages for attendance code error

### ISSUE THREAD

**Issue by binerys** [ucladevx/membership-portal#4]
## Expected Behavior
If attendance code is not unique, the validation error should specify that. 

## Current Behavior
I get "validation error", which gives no indication on what I filled out incorrectly

## Screenshot(s) 
![screen shot 2017-08-08 at 10 56 05 pm](https://user-images.githubusercontent.com/9737156/29107607-d146e72e-7c8f-11e7-828d-d45de9af91fc.png)

## Steps to Reproduce 
1. Create an event with an attendance code
2. Reuse that attendance code for another event

## Your Environment 
- [x] __Desktop__:  
Operating System:  
- [x] Chrome (__Version:__ )
- [ ] Firefox (__Version:__ )
- [ ] Safari (__Version:__ )
- [ ] Opera (__Version:__ )
- [ ] IE (__Version:__ )
- [ ] EDGE (__Version:__ )

**Comment by nkansal96** [comment]
Resolved: https://github.com/ucladevx/membership-portal/commit/02b3f45a96e86ab72c0bf8956c469d08f17463a2
